### PR TITLE
Survey of resources on RSE and RSEing

### PR DESCRIPTION
**Pull request by jngrad**
Collect resources on RSE-related policies, surveys, training, certification.

### CODE REVIEW

**Comment by jngrad** [comment]
Note: some of these resources do not necessarily reflect RSE or RSEing in their titles. For example, European Commission DGRI 2024 on page 29 section "5.1. National policies on skills and training for open science", they list countries with training programs for RSE/RDM. They don't seem to provide links or citations to the specific training programs that qualified for this table. Some of the resources are present because they are directly cited in RSE-specific resources, like European Commission recommendations or raw survey data.

**Review by CaptainSifff — COMMENTED** [review]
Hi Jean-Noel, all of this is certainly interesting, but so far it's not connected to the text, no?

**Comment by CaptainSifff** [comment]
The other position paper is in lack of some good references: https://github.com/DE-RSE/2023_paper-RSE-groups/issues/21
maybe you have ideas for some of the refs? Thank You!

**Comment by jngrad** [comment]
> Hi Jean-Noel, all of this is certainly interesting, but so far it's not connected to the text, no?

My idea was to use this BibTeX file as an evidence bank of teaching-related RSE resources, similar to the Software Sustainability Institute [Open Evidence Bank](https://www.software.ac.uk/open-evidence/open-evidence-bank) and resource hub (e.g. [list of RSE journals](https://www.software.ac.uk/top-tip/which-journals-should-i-publish-my-software)), or the UK RSE [resource database](https://society-rse.org/resources-database/). It would be complementary to the survey, in the sense that resources that are featured on the teachingRSE website should be curated and approved by more than one person, while this evidence bank would have a lower barrier to entry. I also find it more convenient to proactively store interesting resources here, rather than trying to find them again at a later point in time when the manuscript takes a direction that makes them relevant.

One could argue a separate, dedicated repository should be used for this task to avoid cluttering the manuscript BibTeX. If you find this repository is not the right place, I will refrain from adding entries that are not cited in the manuscripts.

**Comment by CaptainSifff** [comment]
ah, ok I see.

**Comment by CaptainSifff** [comment]
how about moving the bibliography into its own repository? and then bringing the bibliography in, either via a sub-project or some other mechanism?

**Pull request closed without merging**
