### PR TITLE
Merge terminology sections into one larger section

### PR DESCRIPTION
**Pull request by MakisH**
Touching this, a question would be whether we really want to have this and the `Terminology` as different sections at the same level. I would suggest:

- Terminology
  - The term Research Software Engineering
  - Other terms 

@CaptainSifff @jpthiele opinions?

### CODE REVIEW

**Comment by CaptainSifff** [comment]
Do we have good alternative to "other terms"?

**Comment by jpthiele** [comment]
Further terms?

**Comment by CaptainSifff** [comment]
What about
- Terminology
- - The concept of the Research Software Engineer  (To have less term)
- - other definitions

**Comment by mhagdorn** [comment]
We talked about this before. I understand why we want to have a separate section and was convinced that it is a good idea.

I think if we want to change something we should merge the two sections.

**Comment by MakisH** [comment]
I understand that it is useful to have this as a stand-alone entity, also in the table of contents. My only objection is that these seemingly related sections are at the same hierarchy level.

**Comment by CaptainSifff** [comment]
OK, then let's put it in a hierarchy as you suggested.

**Comment by MakisH** [comment]
Done:

Screenshot from 2024-08-12 17-19-36

**Comment by MakisH** [comment]
Which now generates the question of whether RSE is defined twice:

Screenshot from 2024-08-12 17-21-36

**Comment by CaptainSifff** [comment]
Yes, but I would like to keep it that way. As such we have a directly citable instance of  "Research Software Engineer".

**Pull request merged**
