### PR TITLE
Do not only focus on simulation sciences

### PR DESCRIPTION
**Pull request by knarrff**
The problem here is not the text about simulation sciences (which is rather well written), but that is excludes i) data-oriented sciences and also ii) other research than sciences. The latter might be unintentional, but still needs to be adressed.

Thus I mention those and their close interaction with RDM in an additional abstract. Please do improve the language, my point is merely also mentioning them.

### CODE REVIEW

**Comment by CaptainSifff** [comment]
do we want to have it in the values section? pinging @BeastyBlacksmith for help with the spellchecker.

**Comment by knarrff** [comment]
Concerning the spell checker: it tries to correct a citation key. It might not know it is such a key. I have no idea why it picks this up on this PR (and not others), but it can be also seen in other PRs (and for other keys).

**Comment by BeastyBlacksmith** [comment]
This is caused by a no-break space character on line 1613 of the document. We either remove those or add them to the regex of the action

**Comment by mhagdorn** [comment]
My feeling is that we should have covered this elsewhere already. If not we should definitely add it. @knarrff, did you recently reread the paper and could not find something along those lines elsewhere?

This section is specifically about the values and that RSEs must consider ethical issues when they simulate systems and analyse data.

**Comment by BeastyBlacksmith** [comment]
> We either remove those or add them to the regex of the action

Couldn't figure out how to teach `sed` to do that, so I just removed the no-break space

**Comment by knarrff** [comment]
The issue with sed is fixed: sed understands utf8: I added that (as that character) and that works.

**Comment by mhagdorn** [comment]
Something along those lines might be better placed in Section 4.4 RSE tasks and responsibilities. Somehow we failed to talk about data. We did mention meta data though.

**Pull request merged**
