### PR TITLE
Summarised Version

### PR DESCRIPTION
**Pull request by CaptainSifff**
This PR attempts to create a shortened separate version of the paper focusing on competencies. The summarised version is located in the file summarised_competencies.md

### CODE REVIEW

**Comment by CaptainSifff** [comment]
pinging @sdruskat  and @annalenalamprecht  since you probably know best, which kind of document you had in mind, for the seminar series book.

**Comment by sdruskat** [comment]
> pinging @sdruskat and @annalenalamprecht since you probably know best, which kind of document you had in mind, for the seminar series book.

From the Dagstuhl Seminar, we're soliciting papers for a special issue - not a book - in [*IEEE Computing in Science and Engineering*](https://ieeexplore.ieee.org/xpl/aboutJournal.jsp?punumber=5992) by participants and their collaborators. Author Guidelines are here: https://www.computer.org/csdl/magazine/cs/write-for-us/14597?title=Author%20.

Deadline: 1 Nov 2024

Opinion/perspective papers are welcome, so am Sheffield version would definitely fit the bill. 

Does this answer your question, @CaptainSifff?

**Comment by CaptainSifff** [comment]
Kind of, to know that we only may use 12 references is Important. I was more thinking whether the content fits the discussions you had.

**Comment by sdruskat** [comment]
> Kind of, to know that we only may use 12 references is Important. I was more thinking whether the content fits the discussions you had.

The content of the competencies preprint is certainly in scope for the special issue. If and how the discussions at the seminar can be represented in a special issue paper can better be decided by the members of the Dagstuhl working group, which was led by @jpthiele.

**Comment by MakisH** [comment]
@CaptainSifff that was a bit fast to review without more details on what the differences are.

Looking at the table of contents, I understand that the differences are:

- "Related work" is removed
- "Values" is shorter
- The "Foundational Competencies" sections is exactly (?) the same
- The "How much do people need to know" section is removed
- The "RSE Specializations" is exactly the same (?)

Any other differences?

Is this already in more-or-less the right length? Can I help with any specific parts?

**Comment by CaptainSifff** [comment]
Hi Gerasimos, sorry for that. During todays Meeting we decided to merge it, such that people can open new PRs for their change sagainst it more easily. @knarrff , and @jpthiele work on condensing the specializations, and @mhagdorn works on values and challenges. Also the task-and-reponsibilities section will be cut. Then we can properly name this condensed version "Foundational Competencies of an RSE" and the longer paper is the "Foundational Competencies and Responsibilities of an RSE". The length needs to be cut more down, and we need especially to cut the licenses.

**Comment by MakisH** [comment]
Ah, I see. I started by fixing the CI: https://github.com/the-teachingRSE-project/competencies/pull/366

I am happy to take over any summarizing part (e.g., distill the `Tasks and responsibilities` into a paragraph, instead of completely removing it). I just can mainly work asynchronously these days, meetings are difficult.

**Pull request merged**
